"""LightGBM bonus module with Optuna hyper-parameter search.

This module trains a multiclass LightGBM model on any scenario (features or
embeddings, within or between) previously generated by `scenario_builder`.
It mirrors the metric outputs of the custom kNN implementation by reusing the
`print_metrics` helper for an easy, apples-to-apples comparison.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

import numpy as np

import lightgbm as lgb
import optuna

from models.knn import print_metrics


@dataclass # mm cena que dar init automaticamente as variaveis
class ScenarioDataset:
    """Container for a scenario's train/val/test splits."""

    path: Path
    X_train: np.ndarray
    y_train: np.ndarray
    X_val: np.ndarray
    y_val: np.ndarray
    X_test: np.ndarray
    y_test: np.ndarray
    classes: np.ndarray

    @classmethod
    def from_npz(cls, path: str | Path) -> "ScenarioDataset":
        scenario_path = Path(path)
        if not scenario_path.exists():
            raise FileNotFoundError(f"Scenario file not found: {scenario_path}")
        data = np.load(scenario_path)
        X_train = np.asarray(data["train_X"], dtype=np.float32)
        y_train = data["train_y"].astype(int)
        X_val = np.asarray(data["val_X"], dtype=np.float32)
        y_val = data["val_y"].astype(int)
        X_test = np.asarray(data["test_X"], dtype=np.float32)
        y_test = data["test_y"].astype(int)
        classes = np.unique(np.concatenate([y_train, y_val, y_test])).astype(int)
        classes.sort()
        return cls(
            path=scenario_path,
            X_train=X_train,
            y_train=y_train,
            X_val=X_val,
            y_val=y_val,
            X_test=X_test,
            y_test=y_test,
            classes=classes,
        )

    @property # so pra ser mais facil aceder ao numero de classes
    def num_classes(self) -> int:
        return int(self.classes.size)




def _encode_labels(dataset: ScenarioDataset) -> Dict[str, np.ndarray]:
    """Map original class labels to 0..num_classes-1 via searchsorted. This is the translation LightGBM needs."""
    classes = dataset.classes
    y_train_enc = np.searchsorted(classes, dataset.y_train)
    y_val_enc = np.searchsorted(classes, dataset.y_val)
    y_test_enc = np.searchsorted(classes, dataset.y_test)
    return {
        "train": y_train_enc.astype(np.int32, copy=False),
        "val": y_val_enc.astype(np.int32, copy=False),
        "test": y_test_enc.astype(np.int32, copy=False),
    }

# objetivo do optuna é econtrar os melhores hiperparametros para o lightgbm
# controi varios trials com diferentes hiperparametros e ve qual é o melhor
# ve qual a melhor iteração daquele trial e devolve o modelo treinado com os melhores hiperparametros
def _build_objective(
    dataset: ScenarioDataset,
    encoded_labels: Dict[str, np.ndarray],
    num_boost_round: int,
    early_stopping_rounds: int,
    random_state: int,
):
    train_data = lgb.Dataset(dataset.X_train, label=encoded_labels["train"])
    val_data = lgb.Dataset(dataset.X_val, label=encoded_labels["val"])

    def objective(trial: Any) -> float:
        params = {
            "objective": "multiclass",
            "num_class": dataset.num_classes,
            "metric": "multi_logloss",
            "verbosity": -1,
            "force_row_wise": True,
            "feature_pre_filter": False,
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "num_leaves": trial.suggest_int("num_leaves", 15, 255),
            "max_depth": trial.suggest_int("max_depth", 4, 16),
            "min_child_samples": trial.suggest_int("min_child_samples", 10, 120),
            "feature_fraction": trial.suggest_float("feature_fraction", 0.6, 1.0),
            "bagging_fraction": trial.suggest_float("bagging_fraction", 0.6, 1.0),
            "bagging_freq": trial.suggest_int("bagging_freq", 0, 7),
            "lambda_l1": trial.suggest_float("lambda_l1", 1e-8, 10.0, log=True),
            "lambda_l2": trial.suggest_float("lambda_l2", 1e-8, 10.0, log=True),
            "seed": random_state,
        }

        callbacks = []
        if early_stopping_rounds:
            callbacks.append(lgb.early_stopping(early_stopping_rounds, verbose=False))

        gbm = lgb.train(
            params,
            train_data,
            valid_sets=[val_data],
            num_boost_round=num_boost_round,
            callbacks=callbacks if callbacks else None,
        )
        best_score = gbm.best_score["valid_0"]["multi_logloss"]
        trial.set_user_attr("best_iteration", gbm.best_iteration or num_boost_round)
        return best_score

    return objective

# depois de descobrir os melhores hiperparametros e melhor iteração0 treina o modelo final com todos os dados de treino e validação
def _train_final_model(
    dataset: ScenarioDataset,
    encoded_labels: Dict[str, np.ndarray],
    best_params: Dict[str, Any],
    best_iteration: int,
) -> Any:
    params = best_params.copy()
    params.update(
        {
            "objective": "multiclass",
            "num_class": dataset.num_classes,
            "metric": "multi_logloss",
            "verbosity": -1,
            "force_row_wise": True,
        }
    )

    X_trainval = np.vstack([dataset.X_train, dataset.X_val])
    y_trainval = np.hstack([encoded_labels["train"], encoded_labels["val"]])
    trainval_data = lgb.Dataset(X_trainval, label=y_trainval)

    model = lgb.train(
        params,
        trainval_data,
        num_boost_round=int(best_iteration),
    )
    return model


def _predict_labels(model: Any, dataset: ScenarioDataset) -> np.ndarray:
    raw_pred = model.predict(dataset.X_test)
    if raw_pred.ndim == 1:  # binary fallback, convert to two-class probs
        raw_pred = np.vstack([1 - raw_pred, raw_pred]).T
    pred_indices = np.argmax(raw_pred, axis=1)
    return dataset.classes[pred_indices]


def run_lightgbm_bonus(
    data_processed_path: str | Path,
    data_type: str,
    split_type: str,
    scenario: str,
    n_trials: int = 20,
    timeout: int | None = None,
    random_state: int = 42,
    num_boost_round: int = 1000,
    early_stopping_rounds: int = 50,
    model_output_path: str | Path | None = None,
) -> Dict[str, Any]:
    """Optimize and evaluate LightGBM on a selected scenario.

    Parameters
    ----------
    data_processed_path : str | Path
        Root `data/processed` folder.
    data_type : str
        "features" or "embeddings".
    split_type : str
        "within" or "between".
    scenario : str
        "all", "pca" or "relief".
    n_trials : int, optional
        Optuna trials for hyper-parameter search.
    timeout : int | None, optional
        Maximum optimization time in seconds.
    random_state : int, optional
        Seed used by Optuna and LightGBM.
    num_boost_round : int, optional
        Upper bound on tree boosting rounds during tuning.
    early_stopping_rounds : int, optional
        Early stopping patience on validation log-loss.
    model_output_path : str | Path | None, optional
        Local path to persist the final LightGBM model. If None, the model is not saved.
    """

    data_processed = Path(data_processed_path)
    model_path: Path | None = Path(model_output_path) if model_output_path is not None else None
    scenario_path = data_processed / "scenarios" / data_type / split_type / f"{scenario}.npz"
    dataset = ScenarioDataset.from_npz(scenario_path)
    encoded_labels = _encode_labels(dataset)

    objective = _build_objective(
        dataset,
        encoded_labels,
        num_boost_round=num_boost_round,
        early_stopping_rounds=early_stopping_rounds,
        random_state=random_state,
    )

    sampler = optuna.samplers.TPESampler(seed=random_state)
    study = optuna.create_study(direction="minimize", sampler=sampler)
    optuna.logging.set_verbosity(optuna.logging.WARNING)
    study.optimize(objective, n_trials=n_trials, timeout=timeout, show_progress_bar=True)

    if study.best_trial is None:  # pragma: no cover - defensive check
        raise RuntimeError("Optuna não conseguiu encontrar uma solução válida para o LightGBM.")

    best_iteration = study.best_trial.user_attrs.get("best_iteration", num_boost_round)
    model = _train_final_model(dataset, encoded_labels, study.best_params, int(best_iteration))
    y_pred = _predict_labels(model, dataset)
    accuracy = float(np.mean(y_pred == dataset.y_test))

    print("\n[BONUS][LightGBM] Resultados finais:")
    print(f"  Scenario: {scenario_path.relative_to(data_processed)}")
    print(f"  Melhor logloss (val): {study.best_value:.4f}")
    print(f"  Test accuracy:       {accuracy:.4f}")
    print_metrics(dataset.y_test, y_pred)

    if model_path is not None:
        model_path.parent.mkdir(parents=True, exist_ok=True)
        model.save_model(str(model_path))
        print(f"  Modelo guardado em: {model_path}")

    return {
        "scenario_path": str(scenario_path),
        "best_params": study.best_params,
        "best_iteration": int(best_iteration),
        "best_validation_logloss": float(study.best_value),
        "test_accuracy": accuracy,
        "y_test": dataset.y_test.tolist(),
        "y_pred": y_pred.tolist(),
        "model_path": str(model_path) if model_path is not None else None,
    }


__all__ = ["run_lightgbm_bonus", "ScenarioDataset"]
