"""SMOTE-based balancer for already prepared scenario datasets.

Given any scenario generated by ``meta2.splits.scenario_builder`` (features or
embeddings, within or between), this helper inspects the training split, prints
its class distribution, and applies the existing SMOTE generator to bring every
minority class up to a configurable minimum. The resulting split is persisted to
``data/processed/scenarios/...`` so it can be reused by the LightGBM bonus or
any other experiment.
"""

from __future__ import annotations

import math
from collections import Counter
from pathlib import Path
from typing import Dict, Any

import numpy as np

from meta2.smote import smote_generator


def _load_scenario_arrays(path: Path) -> Dict[str, np.ndarray]:
    with np.load(path, allow_pickle=False) as data:
        return {key: np.array(data[key]) for key in data.files}


def _print_distribution(title: str, labels: np.ndarray) -> Dict[int, int]:
    counts = Counter(int(cls) for cls in labels)
    total = int(labels.size)
    print(f"\n[{title}] Distribuição das classes (train)")
    if total == 0:
        print("Treino vazio; nada para analisar.")
        return counts
    for cls in sorted(counts):
        pct = (counts[cls] / total) * 100 if total else 0.0
        print(f"  Activity {cls}: {counts[cls]} samples ({pct:.2f}%)")
    max_c = max(counts.values()) if counts else 0
    min_c = min(counts.values()) if counts else 0
    if min_c:
        ratio = max_c / min_c
        print(f"  Imbalance ratio (max/min): {ratio:.2f}")
    return counts


def balance_scenario_with_smote(
    data_processed_path: str | Path,
    data_type: str,
    split_type: str,
    scenario: str,
    target_min_ratio: float = 0.75,
    min_target_samples: int | None = None,
    output_scenario_name: str | None = None,
    random_state: int | None = 42,
    k_neighbors: int = 5,
) -> Dict[str, Any]:
    """Apply SMOTE to the training split of a scenario and persist the result."""

    data_processed = Path(data_processed_path)
    scenarios_root = data_processed / "scenarios" / data_type / split_type
    input_path = scenarios_root / f"{scenario}.npz"
    if not input_path.exists():
        raise FileNotFoundError(f"Scenario file not found: {input_path}")

    out_name = output_scenario_name or f"{scenario}_smote"
    output_path = scenarios_root / f"{out_name}.npz"

    arrays = _load_scenario_arrays(input_path)

    if "train_X" not in arrays or "train_y" not in arrays:
        raise KeyError("Scenario is missing train_X/train_y arrays; cannot balance.")

    train_X = np.asarray(arrays["train_X"], dtype=np.float32)
    train_y = np.asarray(arrays["train_y"], dtype=int)
    train_participants = arrays.get("train_participants")
    if train_participants is not None:
        train_participants = np.asarray(train_participants, dtype=int)

    pre_counts = _print_distribution("Antes do SMOTE", train_y)
    if not pre_counts:
        print("[SMOTE Balancer] Treino vazio, apenas copiando cenário original.")
        target_min = 0
        post_counts = pre_counts
        classes_augmented: Dict[int, int] = {}
    else:
        max_count = max(pre_counts.values())
        min_from_ratio = int(math.ceil(max_count * target_min_ratio))
        target_min = max(min_from_ratio, min_target_samples or 0)
        if target_min <= 0:
            target_min = max_count

        classes_augmented: Dict[int, int] = {}
        train_X_bal = train_X
        train_y_bal = train_y
        train_part_bal = train_participants

        for cls, count in sorted(pre_counts.items()):
            if count >= target_min:
                continue
            if count < 2:
                print(f"Classe {cls} tem apenas {count} amostras; SMOTE requer >=2. Ignorada.")
                continue
            needed = target_min - count
            print(f"  → Classe {cls}: +{needed} amostras (target {target_min})")
            prev_len = train_X_bal.shape[0]
            train_X_bal, train_y_bal, train_part_bal = smote_generator.generate_smote_samples(
                train_X_bal,
                train_y_bal,
                activity_label=int(cls),
                K=int(needed),
                k_neighbors=k_neighbors,
                random_state=(random_state + cls) if random_state is not None else None,
                participants=train_part_bal,
            )
            added = train_X_bal.shape[0] - prev_len
            classes_augmented[int(cls)] = added

        train_X = train_X_bal
        train_y = train_y_bal
        train_participants = train_part_bal
        post_counts = _print_distribution("Depois do SMOTE", train_y)

    # Persist new scenario
    payload: Dict[str, np.ndarray] = {}
    payload.update(arrays)
    payload["train_X"] = train_X
    payload["train_y"] = train_y
    if train_participants is not None:
        payload["train_participants"] = train_participants
    np.savez_compressed(output_path, **payload)  # type: ignore[arg-type]
    try:
        rel_path = output_path.relative_to(data_processed)
    except ValueError:
        rel_path = output_path
    print(f"\n[SMOTE Balancer] Cenário balanceado guardado em: {rel_path}")

    return {
        "scenario_name": out_name,
        "input_path": str(input_path),
        "output_path": str(output_path),
        "target_min_count": target_min,
        "classes_augmented": classes_augmented,
        "pre_counts": {int(k): int(v) for k, v in pre_counts.items()},
        "post_counts": {int(k): int(v) for k, v in post_counts.items()},
    }


__all__ = ["balance_scenario_with_smote"]
